# Generated by Django 5.2.5 on 2025-09-02 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(verbose_name='Параметры расчета')),
                ('result', models.JSONField(verbose_name='Результат расчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История расчета',
                'verbose_name_plural': 'История расчетов',
                'ordering': ['-created_at'],
            },
        ),
    ]
