# Generated by Django 5.2.5 on 2025-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.FloatField(default=0.2)),
                ('company_commission_rub', models.FloatField(default=69000.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculator Settings',
                'verbose_name_plural': 'Calculator Settings',
            },
        ),
        migrations.CreateModel(
            name='AcciseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hp', models.FloatField()),
                ('rate_rub_per_hp', models.FloatField()),
            ],
            options={
                'verbose_name': 'Accise Rate',
                'verbose_name_plural': 'Accise Rates',
                'ordering': ['max_hp'],
                'indexes': [models.Index(fields=['max_hp'], name='calculator__max_hp_ce6dc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomsFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value_rub', models.FloatField()),
                ('fee_rub', models.FloatField()),
            ],
            options={
                'verbose_name': 'Customs Fee',
                'verbose_name_plural': 'Customs Fees',
                'ordering': ['max_value_rub'],
                'indexes': [models.Index(fields=['max_value_rub'], name='calculator__max_val_fba289_idx')],
            },
        ),
        migrations.CreateModel(
            name='DutyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PASSENGER_CAR_PHYS', 'Passenger Car (Physical Person)'), ('PASSENGER_CAR_JUR_BENZ', 'Passenger Car (Legal, Petrol)'), ('PASSENGER_CAR_JUR_DIESEL', 'Passenger Car (Legal, Diesel)')], max_length=48)),
                ('age_group', models.CharField(choices=[('under_3_years', 'Under 3 years'), ('3_to_5_years', '3 to 5 years'), ('5_to_7_years', '5 to 7 years'), ('over_7_years', 'Over 7 years'), ('over_5_years', 'Over 5 years')], max_length=32)),
                ('unit', models.CharField(choices=[('eur_cc', 'EUR per cc'), ('percent', '% of price'), ('value', 'Price bracket (EUR)')], max_length=16)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('rate_percent', models.FloatField(blank=True, null=True)),
                ('rate_eur_cc', models.FloatField(blank=True, null=True)),
                ('min_rate_eur_cc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duty Rate',
                'verbose_name_plural': 'Duty Rates',
                'ordering': ['audience', 'age_group', 'unit', 'max_value'],
                'indexes': [models.Index(fields=['audience', 'age_group', 'unit', 'max_value'], name='calculator__audienc_ac14c9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('unit', 'eur_cc'), ('rate_eur_cc__isnull', False), ('rate_percent__isnull', True)), models.Q(('unit__in', ['percent', 'value']), ('rate_percent__isnull', False)), _connector='OR'), name='duty_rate_valid_combination')],
            },
        ),
        migrations.CreateModel(
            name='UtilFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('personal_new', 'Personal (new)'), ('personal_old', 'Personal (old)'), ('commercial_under_3', 'Commercial under 3t'), ('commercial_over_3', 'Commercial over 3t')], max_length=32)),
                ('max_cc', models.FloatField(blank=True, null=True)),
                ('coeff', models.FloatField()),
            ],
            options={
                'verbose_name': 'Utilization Fee',
                'verbose_name_plural': 'Utilization Fees',
                'ordering': ['kind', 'max_cc'],
                'indexes': [models.Index(fields=['kind', 'max_cc'], name='calculator__kind_025e4e_idx')],
            },
        ),
    ]
