# Generated by Django 5.2.5 on 2025-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="util_base",
            field=models.FloatField(default=20000.0),
        ),
    ]
