# Generated by Django 5.2.5 on 2025-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_settings_util_base"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dutyrate",
            name="duty_rate_valid_combination",
        ),
        migrations.AddField(
            model_name="dutyrate",
            name="min_rate_eur_hp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutyrate",
            name="rate_eur_hp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dutyrate",
            name="audience",
            field=models.CharField(
                choices=[
                    ("PASSENGER_CAR_PHYS", "Passenger Car (Physical Person)"),
                    ("PASSENGER_CAR_JUR_BENZ", "Passenger Car (Legal, Petrol)"),
                    ("PASSENGER_CAR_JUR_DIESEL", "Passenger Car (Legal, Diesel)"),
                    ("QUAD_PHYS", "Quad (Physical Person)"),
                    ("QUAD_JUR", "Quad (Legal)"),
                    ("SNOWMOBILE_PHYS", "Snowmobile (Physical Person)"),
                    ("SNOWMOBILE_JUR", "Snowmobile (Legal)"),
                    ("MOTORCYCLE_PHYS", "Motorcycle (Physical Person)"),
                    ("MOTORCYCLE_JUR", "Motorcycle (Legal)"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="dutyrate",
            name="unit",
            field=models.CharField(
                choices=[
                    ("eur_cc", "EUR per cc"),
                    ("percent", "% of price"),
                    ("value", "Price bracket (EUR)"),
                    ("eur_hp", "EUR per hp"),
                    ("percent_hp", "% of price (hp bracket/min in EUR/hp)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="dutyrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("unit", "eur_cc"),
                        ("rate_eur_cc__isnull", False),
                        ("rate_percent__isnull", True),
                        ("rate_eur_hp__isnull", True),
                        ("min_rate_eur_hp__isnull", True),
                    ),
                    models.Q(
                        ("unit", "eur_hp"),
                        ("rate_eur_hp__isnull", False),
                        ("rate_percent__isnull", True),
                        ("rate_eur_cc__isnull", True),
                        ("min_rate_eur_cc__isnull", True),
                    ),
                    models.Q(
                        ("unit__in", ["percent", "value"]),
                        ("rate_percent__isnull", False),
                        ("rate_eur_cc__isnull", True),
                        ("rate_eur_hp__isnull", True),
                    ),
                    models.Q(
                        ("unit", "percent_hp"),
                        ("rate_percent__isnull", False),
                        ("rate_eur_cc__isnull", True),
                        ("rate_eur_hp__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="duty_rate_valid_combination",
            ),
        ),
    ]
