# Generated by Django 5.2.5 on 2025-08-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_remove_dutyrate_duty_rate_valid_combination_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acciserate",
            options={
                "ordering": ["max_hp"],
                "verbose_name": "Акцизная ставка",
                "verbose_name_plural": "Акцизные ставки",
            },
        ),
        migrations.AlterModelOptions(
            name="customsfee",
            options={
                "ordering": ["max_value_rub"],
                "verbose_name": "Таможенный сбор",
                "verbose_name_plural": "Таможенные сборы",
            },
        ),
        migrations.AlterModelOptions(
            name="dutyrate",
            options={
                "ordering": ["audience", "age_group", "unit", "max_value"],
                "verbose_name": "Ставка пошлины",
                "verbose_name_plural": "Ставки пошлины",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "verbose_name": "Настройки калькулятора",
                "verbose_name_plural": "Настройки калькулятора",
            },
        ),
        migrations.AlterModelOptions(
            name="utilfee",
            options={
                "ordering": ["kind", "max_cc"],
                "verbose_name": "Утилизационный сбор",
                "verbose_name_plural": "Утилизационные сборы",
            },
        ),
    ]
